/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TBadge: typeof import('tdesign-mobile-vue')['Badge']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCalendar: typeof import('tdesign-mobile-vue')['Calendar']
    TCascade: typeof import('tdesign-mobile-vue')['Cascade']
    TCascader: typeof import('tdesign-mobile-vue')['Cascader']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TCheckbox: typeof import('tdesign-mobile-vue')['Checkbox']
    TCheckboxGroup: typeof import('tdesign-mobile-vue')['CheckboxGroup']
    TDateTimePicker: typeof import('tdesign-mobile-vue')['DateTimePicker']
    TDialog: typeof import('tdesign-mobile-vue')['Dialog']
    TFooter: typeof import('tdesign-mobile-vue')['Footer']
    TForm: typeof import('tdesign-mobile-vue')['Form']
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
    TIcon: typeof import('tdesign-mobile-vue')['Icon']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TLoading: typeof import('tdesign-mobile-vue')['Loading']
    TPicker: typeof import('tdesign-mobile-vue')['Picker']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TPullDownRefresh: typeof import('tdesign-mobile-vue')['PullDownRefresh']
    TRadio: typeof import('tdesign-mobile-vue')['Radio']
    TRadioGroup: typeof import('tdesign-mobile-vue')['RadioGroup']
    TRate: typeof import('tdesign-mobile-vue')['Rate']
    TStepper: typeof import('tdesign-mobile-vue')['Stepper']
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    TTable: typeof import('tdesign-mobile-vue')['Table']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
    TTextarea: typeof import('tdesign-mobile-vue')['Textarea']
    TUpload: typeof import('tdesign-mobile-vue')['Upload']
  }
}
